services:
  app_hotel:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      DB_URL: jdbc:mysql://hotel_mng:3306/hotel_database?createDatabaseIfNotExist=true
      DB_USER_NAME: root
      DB_PASSWORD: password
    restart: always
    depends_on:
        hotel_mng:
          condition: service_healthy

  hotel_mng:
    image: mysql:8.0.33
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: hotel_database
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 10
